services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 12111211
      MYSQL_DATABASE: notebook
    ports:
      - "3307:3306" # 主機 3307 -> container 3306
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p12111211"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: account-app:1.0
    container_name: account-container
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_URL: jdbc:mysql://mysql:3306/notebook?useSSL=false&serverTimezone=Asia/Taipei&allowPublicKeyRetrieval=true
      DB_USERNAME: root
      DB_PASSWORD: 12111211

volumes:
  mysql-data: